shops:
  world: 
    0:
      0:
        0:
          owner: PenguinOwl
          price: 10
          filter: true
          buy: true
          alerts: false
          chestw: lol
          chestx: 0
          chesty: 0
          chestz: 0
          enabled: false
        